### ISSUE TITLE
When the effect of a rule involves two roles, but the condition doesn't have two separate roles.

### ISSUE THREAD

**Issue by bsamuel** [ensemble-engine/ensemble#10]
Console: If you are writing an effect that involves two people, but the condition doesn’t have two separate roles specified, the effect that involves multiple people won’t display the second role properly. This is actually probably desirable behavior, but even if you do add the additional role in the conditions, the effects won’t update until you’ve fiddled around with it (e.g., switch the category and back)

**Comment by aaronareed** [comment]
Fixed by #65.
