### ISSUE TITLE
Console: Switching between volition and trigger rule tabs sometimes cause files to be re-written incorrectly.

### ISSUE THREAD

**Issue by bsamuel** [ensemble-engine/ensemble#13]
Console: Display bug (which sometimes yields an actual bug). Set up: A schema that has volition file defined, but no trigger file. Click Rule Viewer tab, make a new volition rule by clicking new volition rule button. this takes you to rule editor tab. Without clicking “update rule” go back to rule viewer tab. Now click on the trigger rule tab, and then click make a new trigger rule button. When the dialog comes up to name the trigger file, click cancel. A rule appears to show up in the trigger list, with the same file name as the volition file (but cannot be clicked on, indicating display bug). _HOWEVER_ sometimes (I cannot reliably recreate this) it does seem to save “over” the file (turning your volition file into a trigger file, and eliminating all rules from it except the rule that was appearing as a display bug).

**Comment by aaronareed** [comment]
Fix for #61 also addresses this.
