### ISSUE TITLE
Design Tool adds "value" attributes to volition rule effects, which should not be present.

### ISSUE THREAD

**Issue by bsamuel** [ensemble-engine/ensemble#15]
In the Effects of a volition rule, there… shouldn’t ever be something with a ‘value’ attribute defined. This causes unhappy discrepancies/mismatches. In the validating process of volition rules we should check for that and raise a flag if there is an issue. (Apparently the DESIGN TOOL adds this. Remove it from the design tool?)

**Comment by meldckn** [comment]
Duplicate issue: #72
Fixed by: eba51ec and 2f4766b
