### ISSUE TITLE
Update/clean Yarn schema to be a standard example schema

### ISSUE THREAD

**Issue by bsamuel** [ensemble-engine/ensemble#16]
The ‘yarn’ schemata in the schemata folder has ‘cloneEachTimeStep’ - confirm that that should be changed to duration = 0, and then change it.

**Comment by mkremins** [comment]
We removed the `schemata` folder from the repository entirely as part of our cleanup efforts in https://github.com/ensemble-engine/ensemble/commit/ca95d95fee07976b0aec52dceb3e997d08e8e496, so this doesn't need to happen anymore. Even before we removed it I don't think the Yarn schemata was actually in there.
