### ISSUE TITLE
Module Loading Solution

### ISSUE THREAD

**Issue by bsamuel** [ensemble-engine/ensemble#34]
Research: decide whether to stick with Require or switch to some other system for module loading (CommonJS, other alternatives? maybe we don’t even want a module system, just attach everything to a single global variable “ENSEMBLE”?)

**Comment by mkremins** [comment]
Closing this as of https://github.com/ensemble-engine/ensemble/commit/e1d6bca349d3cafb47bb7843fc3c90bec82ac0c7. We were originally using RequireJS but eventually decided to revert to no module system at all. We might revisit this decision at some point in the future once ES6 modules are more fully supported, but for now, it seems like the easiest thing to do is just concatenate a bunch of JS files together with a fairly naïve build script and release the resulting concatenated file.
