### ISSUE TITLE
Can't add to empty ruleset in authoring tool

### ISSUE THREAD

**Issue by meldckn** [ensemble-engine/ensemble#54]
Can't create new trigger or volition tool from the editor once you've deleted all rules. Produces error "Canceling new rule..."

<img width="921" alt="screen shot 2017-02-23 at 3 19 31 pm" src="https://cloud.githubusercontent.com/assets/3990327/23283575/90408e56-f9db-11e6-98a7-46b78d17600b.png">

**Comment by aaronareed** [comment]
Also fixed by fix for #61.
