### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by rngwrldngnr** [ensemble-engine/ensemble#74]
There currently is no license attached to this repository. That means the only legal right others have is to fork the code or read it. Making changes or using the code for anything is forbidden.

I know based on your papers and the links to download Ensemble from the EIS website that this is meant to be open source and accessible, but would you be willing to make it official?

**Comment by meldckn** [comment]
Done! Thank you so much for your interest and request! Feel free to email me if you have any questions or anything. meldckn at gmail
