### ISSUE TITLE
Clean out node modules

### ISSUE THREAD

**Issue by meldckn** [ensemble-engine/ensemble#94]
Clean out unused npm modules. Surely we don't need all 340 installed in `node_modules` (and that's just the top level!).

I'm not sure how to tell if a particular module is actually used though..

**Comment by mkremins** [comment]
Cleaned out the `node_modules` dependencies in the process of upgrading from NW.js to Electron for [release v1.1.0](https://github.com/ensemble-engine/ensemble/releases/tag/v1.1.0). In the future, we'll have to clean out the dependencies whenever we change them; the easiest way to do this seems to be to remove the `node_modules` folder and the `package-lock.json` file at the repository root, then re-run `npm install` in the terminal.
