### ISSUE TITLE
Make Grunt tool building task work for Windows too

### ISSUE THREAD

**Issue by meldckn** [ensemble-engine/ensemble#95]
When you add `win64` to the `nwjs` `platforms` option of the Gruntfile, it will silently fail without errors when building, and produce a blank nwjs exe. 

It would be very helpful if we didn't have two separate, unrelated processes for building Mac and Windows apps. It would mean you don't have to do two different kinds of updating when you want to update nwjs to support modern JavaScript, for example. 

The only related issue I could find: This might be because Windows does not allow path names over 256 characters, and we probably have well-nested `node_modules` directories (somewhere among our 340 installed npm modules!). See discussions on https://github.com/nwjs-community/nw-builder/issues/107 and https://github.com/nwjs/grunt-nw-builder/issues/118. But I don't think our node modules get packaged with the app? Oh wait I think nwjs automatically looks for a `node_modules` directory and packages it?

**Comment by meldckn** [comment]
Or maybe it'd be better to adopt a different, modern nwjs app build process, since grunt-nw-builder doesn't seem to be super actively maintained anymore?

**Comment by mkremins** [comment]
One neat side effect of the NW.js => Electron upgrade from [release v1.1.0](https://github.com/ensemble-engine/ensemble/releases/tag/v1.1.0): the build processes for the Windows and Mac (and Linux) versions of the authoring tool are now one and the same.
